Q1. Write a python program which takes dictionary as an input and convert it
into a numpy array.


In [3]:
import numpy as np
dic={'a':1,'b':2,'c':3,'D':4,'E':5}
np.array(list(dic.items()))

array([['a', '1'],
       ['b', '2'],
       ['c', '3'],
       ['D', '4'],
       ['E', '5']], dtype='<U21')

In [1]:
import numpy as np
dic={'a':1,'b':2,'c':3,'D':4,'E':5}
converted_array=np.array(list(dic.items()))
print(dic)


{'a': 1, 'b': 2, 'c': 3, 'D': 4, 'E': 5}


In [2]:
converted_array

array([['a', '1'],
       ['b', '2'],
       ['c', '3'],
       ['D', '4'],
       ['E', '5']], dtype='<U21')

Q2. Given a 3D array x of shape (2, 3, 4) and a 2D array y of shape (3, 4). Write
a NumPy program to add them using broadcasting.

In [8]:
a=np.random.randint(1,50,size=[2,3,4])
b=np.random.randint(1,50,size=[3,4])
s=a+b
s

array([[[10, 17, 54, 26],
        [46, 90, 23, 62],
        [56, 91, 40, 32]],

       [[28, 17, 35, 27],
        [31, 83, 17, 45],
        [38, 60, 54, 45]]], dtype=int32)

In [3]:
arr=np.random.randint(1,100,size=[2,3,4])
arr1=np.random.randint(1,50,size=[3,4])
print(arr)
print(arr1)


[[[99 56 50 64]
  [30 89 89 62]
  [62 43 35 24]]

 [[62 55 48 32]
  [72 89 35 30]
  [75 10 59 28]]]
[[16 22 49 39]
 [35 29 29 21]
 [10 39 39 19]]


In [4]:
arr2=arr+arr1
arr2

array([[[115,  78,  99, 103],
        [ 65, 118, 118,  83],
        [ 72,  82,  74,  43]],

       [[ 78,  77,  97,  71],
        [107, 118,  64,  51],
        [ 85,  49,  98,  47]]], dtype=int32)

Q3. Write a python program which finds the nearest element in the array to a
given integer.
Inputs: a=23 and array - [10 17 24 31 38 45 52 59].
Expected Output: Nearest element is 24

In [5]:
import numpy as np
a=int(input("Enter a num :"))
arr=np.array([10,17,24,-31,45,52,59,77])
diff=np.abs(arr-a)
index=np.argmin(diff)
nearest=arr[index]
print(a,"is",nearest)

1 is 10


In [ ]:
n=int(input("Enter a num"))
a=np.array([10,17,24,-31,45,52,59,77])
dif=np.abs(a-n)
index=np.argmin(dif)
ne=arr[index]
print(n,'is',ne)


Q4. Write a python program to replace multiples of 3 or 5 as 0 in the given
array.
Input: arr=[1 2 3 4 5 6 7 9]
Expected Output: [1 2 0 4 0 0 7 0]


In [24]:
arr=np.array([1,2,3,4,5,6,7,9])
arr[[2,4,5,-1]]=[0]
arr

array([1, 2, 0, 4, 0, 0, 7, 0])

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,9])
arr[[2,4,5,-1]]=[0]
arr

array([1, 2, 0, 4, 0, 0, 7, 0])

Q5. Solve the give problem using fancy Indexing:

1. Double the array elements at given indexes
Given:
arr = np.arrange(10)
indexes = [0,3,4,9]
Expected Output: [ 0 1 2 6 8 5 6 7 8 18]

In [40]:
arr=np.arange(10)
indexs=[0,3,4,9]
arr[indexs]=arr[indexs]*2
arr

array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])

In [32]:
arr=np.arange(10)
indexes=[0,3,4,9]
arr[indexes]=arr[indexes]*2
arr


array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])

2. Using a given array make a different array as in below example
Given:
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
• Internal repeation should be as length of the array.


In [41]:
s=np.array([1,2,3])
s.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
arr=np.array([1,2,3])
a1=np.repeat(arr,3)
print(arr)

print(a1)

[1 2 3]
[1 1 1 2 2 2 3 3 3]


In [9]:
print(a1)
len(a1)

[1 1 1 2 2 2 3 3 3]


9

Q6. You are given an array which is having some nan value. You job is to fill
those nan values with mean element in the array.
Given: arr = np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

In [50]:
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
m=np.nanmean(arr)
arr[np.isnan(arr)]=m
arr


array([[1.        , 2.        , 3.33333333],
       [4.        , 2.        , 6.        ],
       [3.33333333, 3.33333333, 5.        ]])

In [10]:
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
arr

array([[ 1.,  2., nan],
       [ 4.,  2.,  6.],
       [nan, nan,  5.]])

In [11]:
mean=np.nanmean(arr)
mean

np.float64(3.3333333333333335)

In [12]:
arr[np.isnan(arr)]=mean
arr


array([[1.        , 2.        , 3.33333333],
       [4.        , 2.        , 6.        ],
       [3.33333333, 3.33333333, 5.        ]])

Q7. Scenario: A sports team tracks player performance across 12 matches.
Task: Create a (12, 5) array with random integers (0 to 100, representing
scores). Mask the values where the player's score is less than the team's
average score for that match. Replace these values with -1.
Expected Output Example: Array with some values replaced by -1.


In [63]:
arr=np.random.randint(1,100,size=(12,5))
print(arr)
avg=arr.mean()
print(avg)


[[42 70 60 46 30]
 [27  9 84 43 55]
 [60 30  2 60 49]
 [61 99  4 55 67]
 [32 91 50 39 88]
 [67 62 43  9 70]
 [35 49 57 13 65]
 [61  3  7 52 28]
 [32 53  3 81 53]
 [56 13 14 56  8]
 [54 56  9  5 76]
 [52  6 73 57 38]]
44.483333333333334


In [65]:
arr[avg>arr]=-1
arr

array([[-1, 70, 60, 46, -1],
       [-1, -1, 84, -1, 55],
       [60, -1, -1, 60, 49],
       [61, 99, -1, 55, 67],
       [-1, 91, 50, -1, 88],
       [67, 62, -1, -1, 70],
       [-1, 49, 57, -1, 65],
       [61, -1, -1, 52, -1],
       [-1, 53, -1, 81, 53],
       [56, -1, -1, 56, -1],
       [54, 56, -1, -1, 76],
       [52, -1, 73, 57, -1]], dtype=int32)

In [ ]:
import numpy as np
arr=np.random.randint(0,100,size=(12,5))
arr

array([[14, 26, 58, 94, 63],
       [ 7, 38, 40, 54, 95],
       [16, 92, 54, 74, 20],
       [30,  1, 37, 43, 16],
       [75, 76, 41, 98, 74],
       [56,  1, 46, 67, 85],
       [26, 72, 17, 50, 44],
       [34, 41, 30, 49, 90],
       [ 4, 14, 94, 22, 48],
       [78, 10, 84, 48, 36],
       [28, 47, 41, 64,  0],
       [83, 45, 86,  8, 74]], dtype=int32)

In [88]:
avg=np.mean(arr)
arr[avg>arr]=-1

In [89]:
arr

array([[-1, -1, -1, 47, 67, -1],
       [-1, -1, -1, -1, -1, -1],
       [95, 96, -1, 40, 48, 50]], dtype=int32)

Q8. Scenario: A business tracks monthly revenue and expenses for 3 departments across 6 months. 
Task: Create two (3, 6) random matrices for revenue and expenses. Perform element-wise multiplication and sum along the row axis to calculate the total profit for each department. 


In [67]:
arr1=np.random.randint(1000,2000,size=(3,6))
arr2=np.random.randint(50000,60000,size=(3,6))
print(arr1)
print(arr2)

[[1109 1491 1645 1042 1280 1131]
 [1764 1752 1051 1092 1186 1973]
 [1360 1680 1082 1230 1032 1103]]
[[56158 53591 51501 59829 56774 58106]
 [54557 54119 56159 57987 52466 57888]
 [55326 56323 57735 54643 55727 53199]]


In [70]:
arr=arr1*arr2
np.sum(arr,axis=1)

array([427632972, 489837649, 415734921])

In [ ]:
arr1=np.random.randint(1000,2000,size=(3,6))
arr2=np.random.randint(50000,60000,size=(3,6))
print(arr1)
print(arr2)


[[1878 1526 1689 1221 1988 1147]
 [1898 1207 1140 1174 1117 1175]
 [1904 1732 1151 1851 1056 1534]]
[[58529 55361 59025 55910 56765 51704]
 [50038 52643 54232 56349 53954 56890]
 [55463 51012 58311 59720 52993 57622]]


In [27]:
mul=arr1*arr2
np.sum(mul,axis=1)

array([534510991, 413602799, 515964773])

In [21]:
r1=arr[0]
print(r1)
sum(r1)

[27 36 24 47 67 22]


np.int32(223)


Q10. Scenario: A company tracks salaries of 15 employees in 3 departments. Task: Create a (3, 15) matrix of random salaries. Identify and print the department(s) where all employees have salaries above ₹50,000. Replace salaries less than ₹30,000 with the department's average salary. 
 
Expected Output Example: Original Salary matrix and Updated salary matrix. 



In [90]:
s=np.random.randint(20000,40000,size=(3,15))
avg=np.mean(s,axis=1)
avg

array([30872.93333333, 28401.93333333, 31053.13333333])

In [91]:
max_avg=avg.max()
max_avg

np.float64(31053.133333333335)

In [92]:
s[s<30000]==max_avg

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [93]:
s

array([[28492, 29265, 34092, 25423, 20534, 32411, 37533, 31931, 29484,
        32439, 30145, 24068, 38566, 35247, 33464],
       [22105, 25452, 32288, 33610, 22238, 32587, 24585, 24816, 33173,
        20390, 22596, 35127, 37458, 21968, 37636],
       [33312, 30451, 37704, 30384, 36811, 29819, 34738, 21271, 25112,
        28180, 29180, 27673, 32854, 30813, 37495]], dtype=int32)

s=np.arange(1,17).reshape(4,4)
s
# fancindexing
s[[0,3]]
# booleanindexing
s>10
s.shape
s[s>10]
# ravel fun to convert a 2d ya 30 any type to convet a  1 d array 
np.ravel(s)
arr=np.arange(1,10)
arr
np.cumsum(arr)
np.cumprod(arr)
arr.shape
a=np.expand_dims(arr,axis=0)
a.shape

WHY NUMPY IS FASTER ?

numpy array are store in continous place in memory unlike lists so process can access and manipualte them very effencently .
this behavior is called locality of refrence in computer science 

numpy are a more than 50 times  faster
array are less memory use 22