I. Create a 4x4 matrix representing a game board with values ran
ging from 0 to 15. Extract and print the bottom-right 2x2 subboard.


In [1]:
import numpy as np

In [6]:
s1=np.arange(0,16).reshape(4,4)
s1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
s1[2:,2:]

array([[10, 11],
       [14, 15]])

In [4]:
s=np.arange(0,16).reshape(4,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
s[2:,2:]

array([[10, 11],
       [14, 15]])

II. Generate an array with 20 random integers between 10 and 50.
Slice out every alternate element starting from the second ele
ment and print the result.


In [11]:
s=np.random.randint(10,50,size=20)
s

array([25, 28, 32, 18, 32, 32, 20, 47, 10, 44, 16, 25, 27, 33, 45, 32, 10,
       22, 31, 39], dtype=int32)

In [12]:
s[1::2]

array([28, 18, 32, 47, 44, 25, 33, 32, 22, 39], dtype=int32)

In [12]:
arr=np.random.randint(10,50,size=20)
arr

array([38, 14, 16, 20, 31, 45, 22, 19, 44, 30, 23, 49, 34, 25, 31, 20, 41,
       21, 24, 39], dtype=int32)

In [14]:
slicing_arr=arr[1::2]
slicing_arr

array([14, 20, 45, 19, 30, 49, 25, 20, 21, 39], dtype=int32)

III. Create a 4x4 matrix with elements range between 16 to 31.
Extract and print the middle 2x2 sub-matrix.

In [15]:
s1=np.arange(16,32).reshape(4,4)
s1

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [16]:
s1[1:3,1:3]

array([[21, 22],
       [25, 26]])

In [17]:
arr=np.arange(16,32).reshape(4,4)
arr

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
arr[1:3,1:3]

array([[21, 22],
       [25, 26]])

IV. 3D array representing RGB colour channels of a 2x3 image. Slice
and print the green channel (second channel).

In [18]:
s1=np.random.randint(1,50,size=[3,3,3])
s1

array([[[37, 22, 47],
        [14, 27, 23],
        [13, 48, 18]],

       [[32, 35,  3],
        [43, 32, 33],
        [41,  5, 18]],

       [[13, 36,  7],
        [48, 30,  1],
        [13, 29, 30]]], dtype=int32)

In [38]:
s1[:,:,1]

array([[22, 27, 48],
       [35, 32,  5],
       [36, 30, 29]], dtype=int32)

In [24]:
arr=np.random.randint(1,50,size=[3,3,3])
arr

array([[[18, 49, 22],
        [49, 44,  9],
        [38, 38, 36]],

       [[42, 41,  8],
        [38, 21, 25],
        [35, 34,  9]],

       [[13, 21, 11],
        [10, 41, 15],
        [ 1, 48, 49]]], dtype=int32)

In [27]:
green_chanel=arr[:,:,1]
green_chanel

array([[49, 44, 38],
       [41, 21, 34],
       [21, 41, 48]], dtype=int32)

V. Create a 4x4x4 array of random elements. Extract and print a
2x2x2 sub-array from the centre of the array.


In [40]:
s1=np.random.randint(1,50,size=[4,4,4])
s1

array([[[ 5, 24, 16, 18],
        [25, 33, 28, 36],
        [22, 26, 27, 42],
        [34, 34,  6,  6]],

       [[16, 29, 38, 43],
        [18, 49, 17, 34],
        [ 3, 46,  1, 31],
        [40, 44, 17, 26]],

       [[49, 31, 30, 20],
        [ 2, 33,  4, 40],
        [23, 31, 36, 19],
        [17, 14, 15,  6]],

       [[23, 21, 40, 26],
        [44, 18, 28, 38],
        [ 1, 36, 32, 16],
        [11,  5, 34, 17]]], dtype=int32)

In [42]:
s1[1:3,1:3,1:3]

array([[[49, 17],
        [46,  1]],

       [[33,  4],
        [31, 36]]], dtype=int32)

In [30]:
random_num=np.random.randint(1,50,size=[4,4,4])
random_num

array([[[41,  2, 49, 25],
        [34, 14, 40, 48],
        [37, 35,  2,  1],
        [44,  1, 27, 49]],

       [[ 4, 30, 24,  6],
        [42, 33, 35, 34],
        [11, 15, 16, 10],
        [25,  6,  5,  7]],

       [[14,  9,  3, 17],
        [19, 41, 32,  6],
        [34, 23, 33,  4],
        [37, 14, 38, 27]],

       [[29, 44, 11, 11],
        [41, 24, 48, 12],
        [18, 13,  3,  5],
        [15, 25, 27, 17]]], dtype=int32)

In [33]:
random_num[1:3,1:3,1:3]

array([[[33, 35],
        [15, 16]],

       [[41, 32],
        [23, 33]]], dtype=int32)

VI. Write a program which replace odd elements 2D array with -1.


In [49]:
s=np.arange(1,21).reshape(4,5)
s[s%2!=0]=-1
s

array([[-1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1],
       [16, -1, 18, -1, 20]])

In [40]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
arr[arr%2!=0 ]=-1
arr

array([[-1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1],
       [16, -1, 18, -1, 20]])

VII. You have a 7x7 grid representing scoreboard. Print the values o
f the main diagonal (from top-left to bottom-right).

In [51]:
s=np.arange(1,50).reshape(7,7)
s.diagonal()

array([ 1,  9, 17, 25, 33, 41, 49])

In [45]:
arr=np.arange(1,50).reshape(7,7)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [50]:
arr.diagonal()

array([ 1,  9, 17, 25, 33, 41, 49])

VIII. Ask user to input two numbers a, b. Write a program to
generate a random array of shape (a, b) and print the array and
average of the array

In [52]:
a=int(input("Enter a row:"))
b=int(input("Enter a Column:"))
arr=np.random.randint(1,50,size=(a,b))
arr

array([[20,  2, 34, 12, 43],
       [19, 14, 13, 43, 44],
       [32, 32, 21, 33,  8],
       [17, 44, 22, 31, 22],
       [25, 30, 21,  2, 31]], dtype=int32)

In [53]:
arr.mean()

np.float64(24.6)

In [78]:
a=int(input("Enter a row:"))
b=int(input("Enter a Column:"))
arr=np.random.randint(1,50,size=(a,b))
arr

array([[28, 20, 38, 16, 24],
       [24, 26, 45,  3, 24],
       [11, 44,  1, 49, 27]], dtype=int32)

In [79]:
Avarage=np.mean(arr)
Avarage

np.float64(25.333333333333332)

IX. Write a program to Create a null vector of size 10 but the fifth
value which is 1.

In [56]:
s=np.zeros(10)
s[4]=1
s

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [87]:
Null_vector=np.zeros(10)
Null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
Null_vector[4]=1
Null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

X. Write a program to create a 5x5 matrix with row values ranging
from 0 to 4.

In [57]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [106]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

XI. Write a program which Swap first column of array with second
column in the array of 3x3 matrix.

In [63]:
s=np.arange(1,10).reshape(3,3)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
s[:,[0,1]]=s[:,[1,0]]
s

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [136]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr[:,[0,1]]=arr[:,[1,0]]
arr

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [138]:
arr[[1,2]]=arr[[2,1]]
arr

array([[2, 1, 3],
       [8, 7, 9],
       [5, 4, 6]])