Q1. Write a program which Subtract the mean of each row from a
matrix. (Create a matrix of random elements)

In [1]:
import numpy as np


In [34]:
s1=np.arange(1,21).reshape(4,5)
s1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
s2=s1.mean(axis=0)
s2

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [48]:
s3=s1-s2
s3

array([[-7.5, -7.5, -7.5, -7.5, -7.5],
       [-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 7.5,  7.5,  7.5,  7.5,  7.5]])

In [25]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
m=arr.mean(axis=0)
m

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [32]:
subtract=arr-m
subtract

array([[-7.5, -7.5, -7.5, -7.5, -7.5],
       [-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 7.5,  7.5,  7.5,  7.5,  7.5]])

Q2. Write a python program to count the number of elements in 2D
array.
Test case:
Input: np.array([1, 2])
Expected Output: 2

In [51]:
a1=np.random.randint(1,20,size=[4,5])
a1

array([[ 7, 13, 10, 14,  1],
       [16,  1, 16,  6, 10],
       [18, 10,  6, 11, 10],
       [12,  1, 17,  7, 17]], dtype=int32)

In [53]:
a1.size

20

In [22]:
arr=np.random.randint(1,20,size=[4,4])
arr

array([[12,  6,  2,  2],
       [15, 17, 12, 19],
       [13, 18, 13, 19],
       [16, 16, 19, 12]], dtype=int32)

In [ ]:
# count ka liya size ka use kiya jata ha 
arr.size

16

Q3. You are given a space separated list of numbers. Your task is to
print a reversed NumPy array with the element type float.
Test Case:
Input: 1 2 3 4 5 6 7 8
Expected Output: [8.0 7.0 6.0 5.0 4.0 3.0 2.0 1.0]


In [56]:
arr=np.array([1,2,3,4,5,6,7,8],dtype=float)
print(arr)
arr[::-1]

[1. 2. 3. 4. 5. 6. 7. 8.]


array([8., 7., 6., 5., 4., 3., 2., 1.])

In [54]:
arr=np.array([1,2,3,4,5,6,7,8],dtype=float)
arr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [52]:
arr[::-1]

array([8., 7., 6., 5., 4., 3., 2., 1.])

Q4. Create the following pattern without hardcoding. Use only
numpy functions and the below input array a.
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [69]:
a=np.array([1,2,3])
print(a)
a1=a.repeat(3)
print(a1)
a2=np.tile(a,3)
print(a2)
a3=np.concatenate([a1,a2])
a3

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [55]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [65]:
a1=np.repeat(a,3)#repeat mean repeat karna 
a2=np.tile(a,3)#tile mean seam to same repeat karna
a1
a2

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [66]:
np.concatenate([a1,a2])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q5. Write a function to create a 2d array with 1 on the border and 0
inside. Take 2-D array shape as (a, b) as parameter to function.
Input: a = 4
 b = 4
Expected Output:
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]

In [74]:
a=4
b=4
arr=np.ones([a,b],dtype=int)
arr
arr[1:3,1:3]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [78]:
a=4
b=4
arr=np.ones([a,b],dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [82]:
arr[1:3,1:3]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Q6. Write a function which will accept 2 arguments.
First: A 1D numpy array arr
Second: An integer n {Please make sure n<=len(arr)}
Output: The output should be the nth largest item out of the array.
Test Case:
Input: arr = (12,34,40,7,1,0) and n=3,
Output; 12
Test case:
Input: arr=(12,34,40,7,1,0) and n=1
Output: 40

In [93]:
import numpy as np
def num(arr,n):
    if n>=len(arr):
        raise ValueError('n should be less than or equal to length of arr')
    sorted_arr=np.sort(arr)[::-1]
    return sorted_arr[n-1] 
arr=np.array([12,34,40,7,1,0])
n=int(input("Entera  num"))
num(arr,n)

np.int64(1)

In [32]:
import numpy as np
def num(arr,n):
    if n> len(arr):
        raise ValueError("n should be less than or equal to length of arr")
    sorted_arr=np.sort(arr)[::-1]
    return sorted_arr[n-1]
arr=np.array([12,34,40,71,1,0])
n=int(input("Enter a num"))
num(arr,n)


np.int64(12)

Q7. Write a program which makes an array having corresponding 
max value out of two given arrays. 
Input:  
a=np.array([6,3,1,5,8]) 
b=np.array([3,2,1,7,2]) 
Output: [6 3 1 7 8] 

In [95]:
a=np.array([6,3,1,5,8]) 
b=np.array([3,2,1,7,2]) 
max_value=np.maximum(a,b)
max_value

array([6, 3, 1, 7, 8])

In [13]:
import numpy as np

a=np.array([6,3,1,5,8]) 
b=np.array([3,2,1,7,2]) 
maximum_value=np.maximum(a,b)
maximum_value


array([6, 3, 1, 7, 8])

Q8. Write a python function that accepts infinite number of numpy 
arrays and do the vertical stack to them. Then return that new array 
as result. The function only accepts the numpy array, otherwise raise 
error. 
Test Case: 
Input: a= [[0 1 2 3 4]    
[5 6 7 8 9]] 
b= [[1 1 1 1 1] 
[1 1 1 1 1]] 
Output: [[0 1 2 3 4] 
[5 6 7 8 9] 
[1 1 1 1 1] 
[1 1 1 1 1]] 

In [100]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
b=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
import numpy as np
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
b=np.array([[1,1,1,1,1],[1,1,1,1,1]])
a
b


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])